field: 00b79000-06ca-4d0c-a04a-9fce39f91725 # Video Embeds
fieldLayouts:
  7238fcde-55cd-4b9a-8e63-719ab7a84950:
    tabs:
      -
        elements:
          -
            fieldUid: 7a8f7a07-ae16-45d7-8c8c-14214089d319 # FB - Embed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7a8f7a07-ae16-45d7-8c8c-14214089d319: # FB - Embed
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fbEmbed
    instructions: ''
    name: 'FB - Embed'
    searchable: false
    settings:
      mode: htmlmixed
    translationKeyFormat: null
    translationMethod: none
    type: luwes\codemirror\fields\CodeMirrorField
handle: facebook
name: Facebook
sortOrder: 3
