field: 00b79000-06ca-4d0c-a04a-9fce39f91725 # Video Embeds
fieldLayouts:
  5c067b39-3263-43e6-bb84-9c59f03c5997:
    tabs:
      -
        elements:
          -
            fieldUid: cc452521-cc64-416e-95da-07bd826fcb91 # FB Embed from Iframely - Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  cc452521-cc64-416e-95da-07bd826fcb91: # FB Embed from Iframely - Code
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: fbIframely
    instructions: 'For non 16X9 videos on Facebook, use the Iframely embed service here --> https://iframely.com/domains/facebook'
    name: 'FB Embed from Iframely - Code'
    searchable: false
    settings:
      mode: htmlmixed
    translationKeyFormat: null
    translationMethod: none
    type: luwes\codemirror\fields\CodeMirrorField
handle: fbiFramely
name: 'Facebook IFramely'
sortOrder: 6
