field: 00b79000-06ca-4d0c-a04a-9fce39f91725 # Video Embeds
fieldLayouts:
  9efc4dae-e95c-42ce-b66f-5d8784a49673:
    tabs:
      -
        elements:
          -
            fieldUid: 2b280577-fb62-4a0b-b082-3f12203e2ec6 # Insta - Embed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2b280577-fb62-4a0b-b082-3f12203e2ec6: # Insta - Embed
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: instaEmbed
    instructions: ''
    name: 'Insta - Embed'
    searchable: false
    settings:
      mode: htmlmixed
    translationKeyFormat: null
    translationMethod: none
    type: luwes\codemirror\fields\CodeMirrorField
handle: instagram
name: Instagram
sortOrder: 4
