field: 00b79000-06ca-4d0c-a04a-9fce39f91725 # Video Embeds
fieldLayouts:
  c85de4c0-b084-4a08-aabe-b2f8099d3e0d:
    tabs:
      -
        elements:
          -
            fieldUid: 80b3706f-9a9d-4510-8343-516e60df19aa # TW - Embed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  80b3706f-9a9d-4510-8343-516e60df19aa: # TW - Embed
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: twEmbed
    instructions: ''
    name: 'TW - Embed'
    searchable: false
    settings:
      mode: htmlmixed
    translationKeyFormat: null
    translationMethod: none
    type: luwes\codemirror\fields\CodeMirrorField
handle: twitter
name: Twitter
sortOrder: 4
