field: 00b79000-06ca-4d0c-a04a-9fce39f91725 # Video Embeds
fieldLayouts:
  1869b9ea-b8c6-4659-b5d1-8d478f4125f4:
    tabs:
      -
        elements:
          -
            fieldUid: adb26397-68d4-4ecb-a184-e985116b29ed # Vim - Embed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  adb26397-68d4-4ecb-a184-e985116b29ed: # Vim - Embed
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: vimEmbed
    instructions: ''
    name: 'Vim - Embed'
    searchable: false
    settings:
      mode: htmlmixed
    translationKeyFormat: null
    translationMethod: none
    type: luwes\codemirror\fields\CodeMirrorField
handle: vimeo
name: Vimeo
sortOrder: 2
