field: 00b79000-06ca-4d0c-a04a-9fce39f91725 # Video Embeds
fieldLayouts:
  925c8990-d0e7-42bf-9caa-673cc6d3ddf6:
    tabs:
      -
        elements:
          -
            fieldUid: 6187e7ab-037d-4480-af92-0fc36abd9b85 # YT - Embed
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6187e7ab-037d-4480-af92-0fc36abd9b85: # YT - Embed
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: ytEmbed
    instructions: ''
    name: 'YT - Embed'
    searchable: false
    settings:
      mode: htmlmixed
    translationKeyFormat: null
    translationMethod: none
    type: luwes\codemirror\fields\CodeMirrorField
handle: youtube
name: YouTube
sortOrder: 1
